- name: Restart Windows Server via SSH
  hosts: windows_servers
  gather_facts: no
  vars:
    ansible_connection: winrm
  tasks:
    - name: Restart the Windows server
      ansible.windows.win_command: shutdown /r /t 0 /f
