- name: Restart Windows Server via SSH
  hosts: windows_servers
  gather_facts: no
  vars:
    ansible_connection: ssh
    ansible_port: 22
  tasks:
    - name: Ping 8.8.8.8 from Windows server
      ansible.builtin.shell: ping -n 4 8.8.8.8
