- name: Restart Windows Server via SSH
  hosts: windows_servers
  gather_facts: no
  tasks:
    - name: Restart the Windows server
      ansible.builtin.shell: shutdown /r /t 0 /f
      become: false
