- name: Restart Windows Server via SSH
  hosts: windows_servers
  gather_facts: no
  vars:
    ansible_connection: winrm
  tasks:
    - name: Ping 8.8.8.8 from Windows server
      ansible.windows.win_command: ping -n 4 8.8.8.8
